from database import SessionLocal, engine
from core.demo_agent import seed_demo_agent, run_tests as generate_traces
from core.evaluator import EvaluationEngine
from models import Agent, TestScenario, ExecutionTrace, Base
import json

if __name__ == "__main__":
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    seed_demo_agent(db)
    
    agent = db.query(Agent).filter(Agent.name == "Commerce Support Agent").first()
    
    # Run sandbox to get traces
    generate_traces(db)
    
    scenarios = db.query(TestScenario).filter(TestScenario.agent_id == agent.id).all()
    traces = db.query(ExecutionTrace).filter(ExecutionTrace.test_scenario_id.in_([s.id for s in scenarios])).all()
    
    engine = EvaluationEngine()
    
    print("\n--- Running Evaluation Engine ---")
    # Get the latest 3 traces generated by generate_traces
    for trace in traces[-3:]: 
        sc = db.query(TestScenario).filter(TestScenario.id == trace.test_scenario_id).first()
        print(f"\nEvaluating trace for Scenario: {sc.category} | {sc.user_input}")
        
        failures = engine.evaluate_trace(sc, trace.trace_data)
        
        if not failures:
            print("  Result: PASS (No failures detected)")
        else:
            print(f"  Result: FAIL ({len(failures)} failures detected)")
            for i, f in enumerate(failures):
                print(f"    {i+1}. [{f['category']}] ({f['severity']}): {f['description']}")
                print(f"       Evidence: {f['evidence']}")
                print(f"       Expected: {f['expected_behavior']}")
                print(f"       Actual  : {f['actual_behavior']}")
                print(f"       Fix     : {f['recommendation']}")
                
    db.close()
    print("\nPhase 4 test complete.")
